name: Check Accessibility

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install pa11y
        run: npm install -g pa11y
      
      - name: Check accessibility (index.html)
        run: |
          # Start a simple HTTP server
          npx http-server -p 8080 &
          SERVER_PID=$!
          
          # Wait for server to start
          sleep 5
          
          # Run accessibility check
          pa11y --reporter cli http://localhost:8080/index.html
          
          # Kill the server
          kill $SERVER_PID
