name: Check Performance

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  performance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli
      
      - name: Start HTTP server
        run: |
          npx http-server -p 8080 &
          SERVER_PID=$!
          echo "SERVER_PID=$SERVER_PID" >> $GITHUB_ENV
          
          # Wait for server to start
          sleep 5
      
      - name: Run Lighthouse CI
        run: |
          lhci autorun --config=./lighthouserc.json --collect.url=http://localhost:8080/index.html
      
      - name: Stop HTTP server
        run: kill ${{ env.SERVER_PID }}
        if: always()  # Ensure server is stopped even if previous steps fail
