name: Test GitHub Pages Setup

on:
  # This workflow is only for testing and won't run automatically
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: List files
        run: |
          echo "Repository contents:"
          ls -la
          
      - name: Verify CNAME
        run: |
          echo "CNAME content:"
          cat CNAME
          
      - name: Verify index.html exists
        run: |
          if [ -f "index.html" ]; then
            echo "index.html exists"
          else
            echo "index.html does not exist"
            exit 1
          fi
